viaje_homepage:
    path:     /
    defaults: { _controller: ViajeBundle:Default:index }
buscar_modelo:
    path:     /buscarmodelo
    defaults: { _controller: ViajeBundle:Default:datos }
buscar_hoteles:
    path:     /hoteles
    defaults: { _controller: ViajeBundle:Default:hoteles }
reportes_hoteles:
    path:     /reportes/{id}
    defaults: { _controller: ViajeBundle:Default:reporte }
